use_frameworks!

platform :ios, '10.0'
source 'https://github.com/LuShanshan633/LSSSpecs.git'

target 'LSSTitleSlider_Example' do
 pod 'LSSTitleSlider', :path => '../'
  target 'LSSTitleSlider_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
