use_frameworks!

platform :ios, '8.0'

target 'LSSTitleSlider_Example' do
  pod 'LSSTitleSlider', :path => '../'

  target 'LSSTitleSlider_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
